### ISSUE TITLE
Just saying thanks

### ISSUE THREAD

**Issue by Thomashighbaugh** [kir4h/docker-hackmyresume-all-themes#1]
This was the **only way** I was able to build the vast majority of these themes, I guess the root project isn't aging well but I was after a decent HTML resume at least to start with and build from there. Well thanks to your wisdom in putting these suckers into a docker container, I was able to get more than I needed. 

## Appreciate it!

**Comment by kir4h** [comment]
Glad it was helpful @Thomashighbaugh !  Been a while since last time I worked on it, but I remember I had some issues and that´s why decided to dockerize it to have something that more or less works (I remember some of the themes didn´t look very well but others were ok´ish) 

Thanks for taking your time to comment!
